### ISSUE TITLE
Most pages (search, concept) are "always loading" - unclear what is hanging

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/ocl_web#25] opened 2015-01-12 14:13 UTC
Not sure when/why this is happening yet. Need more data.

**Comment by paynejd** [comment] 2015-01-13 17:17
Not sure what is happening, and I cannot reproduce it reliably. Nothing breaks when it "hangs" though, so let's bump to next milestone.

**Comment by paynejd** [comment] 2015-02-12 14:36
This has not happened since-- I'm going to close this.

**Closed by paynejd** 2015-02-12 14:36 UTC
Labels: bug
